[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ysz-predict"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kedrogy-contracts",
    "transformers==4.57.1",
    "torch>=1.13.1",
    "fastapi[standard]>=0.115.14",
]

[tool.uv]
package = true

[project.scripts]
serve = "ysz.predict.serve:main"

[tool.uv.build-backend]
module-name = "ysz.predict"

[[tool.uv.index]]
name = "ysz"
url = "https://pypi.ysz.vc/"
publish-url = "https://pypi.ysz.vc/"
explicit = true

[tool.uv.sources]
kedrogy-contracts = { path = "../contracts", editable = true }
