# syntax=docker/dockerfile:1
# Dockerfile for Tilt 

FROM python:3.12-slim

RUN apt-get update && apt install -y postgresql-common \
    && YES=yes /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh \
    && apt-get install -y --no-install-recommends \
    libpq-dev \
    postgresql-client-18 \
    g++ \
    ripgrep \
    git \
    openssh-client \
    curl \
    && rm -rf /var/lib/apt/lists/*
    
COPY --from=ghcr.io/astral-sh/uv:0.9.28 /uv /uvx /bin/

# https://docs.docker.com/build/ci/github-actions/secrets/
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

#TODO to kedrogy-cache pvc , inspec usages of 
#AutoTokenizer.from_pretrained etc and download if needed 
RUN --mount=type=cache,target=/root/.cache/uv bash <<EOF
mkdir /tmp/hf
cd /tmp/hf
uv init --python=3.12 --vcs none
uv add huggingface_hub
uv sync
EOF

RUN HF_HUB_DISABLE_XET=1 /tmp/hf/.venv/bin/python <<EOF
from huggingface_hub import snapshot_download


def main():
    # https://github.com/huggingface/huggingface_hub/issues/139
    model_path = snapshot_download(
        repo_id="bert-base-multilingual-uncased",
        allow_patterns=[
            "tokenizer_config.json",
            "config.json",
            "vocab.txt",
            "tokenizer.json",
            "*.safetensors",
        ],
    )

if __name__ == "__main__":
    main()
EOF

WORKDIR /app

COPY contracts /contracts
COPY example/pyproject.toml example/uv.lock /app/
COPY example/mykedro/pyproject.toml /app/mykedro/
COPY example/mykedro/src /app/mykedro/src
COPY example/mykedro/conf/base /app/mykedro/conf/base
COPY example/myrecipes/pyproject.toml example/myrecipes/README.md /app/myrecipes/
COPY example/myrecipes/src /app/myrecipes/src
COPY predict/pyproject.toml predict/README.md /predict/
COPY predict/src /predict/src
RUN mkdir -p /app/mykedro/conf/local /app/mykedro/data/00_examples /app/mykedro/data/02_intermediate /app/mykedro/data/05_model_input /app/mykedro/data/06_models

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=ssh \
    --mount=type=secret,id=prodigy_username,env=UV_INDEX_PRODIGY_USERNAME \
    --mount=type=secret,id=ysz_username,env=UV_INDEX_YSZ_USERNAME \
    --mount=type=secret,id=ysz_password,env=UV_INDEX_YSZ_PASSWORD \
    uv sync --all-packages --no-dev --locked

ENTRYPOINT ["/app/.venv/bin/python"]
