# Dockerfile for Tilt 

FROM python:3.12-slim

RUN apt-get update && apt install -y postgresql-common \
    && YES=yes /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh \
    && apt-get install -y --no-install-recommends \
    libpq-dev \
    postgresql-client-18 \
    g++ \
    ripgrep \
    git \
    openssh-client \
    curl \
    && rm -rf /var/lib/apt/lists/*
    
COPY --from=ghcr.io/astral-sh/uv:0.9.28 /uv /uvx /bin/

# https://docs.docker.com/build/ci/github-actions/secrets/
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

#TODO to kedrogy-cache pvc , inspec usages of 
#AutoTokenizer.from_pretrained etc and download if needed 
RUN bash <<EOF
mkdir /tmp/hf
cd /tmp/hf
uv init --python=3.12
uv add huggingface_hub
uv sync
EOF

RUN /tmp/hf/.venv/bin/python <<EOF
from huggingface_hub import snapshot_download


def main():
    # https://github.com/huggingface/huggingface_hub/issues/139
    model_path = snapshot_download(
        repo_id="bert-base-multilingual-uncased",
        allow_patterns=[
            "tokenizer_config.json",
            "config.json",
            "vocab.txt",
            "tokenizer.json",
            "*.safetensors",
        ],
    )

if __name__ == "__main__":
    main()
EOF

WORKDIR /app

# ARG UV_INDEX_PRODIGY_USERNAME 
# RUN --mount=type=cache,target=/root/.cache/uv \
#     --mount=type=bind,source=mysite/uv.lock,target=mysite/uv.lock \
#     --mount=type=bind,source=mysite/pyproject.toml,target=mysite/pyproject.toml \
#     cd mysite && \
#     uv sync --dev --frozen

COPY ./example /app

COPY ./predict /predict

# # https://docs.docker.com/build/ci/github-actions/secrets/
# # this step configure git and checks the ssh key is loaded
# RUN --mount=type=ssh <<EOT
#   set -e
#   echo "Setting Git SSH protocol"
#   git config --global url."git@github.com:".insteadOf "https://github.com/"
#   (
#     set +e
#     ssh -T git@github.com
#     if [ ! "$?" = "1" ]; then
#       echo "No GitHub SSH key loaded exiting..."
#       exit 1
#     fi
#   )
# EOT
ARG UV_INDEX_PRODIGY_USERNAME 
ARG UV_INDEX_YSZ_USERNAME
ARG UV_INDEX_YSZ_PASSWORD
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=ssh \
    uv sync --all-packages --dev --locked

ENTRYPOINT [ "/app/.venv/bin/python" ]
