[project]
name = "dev"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mysite", 
    # "predict",
    
    # uv does not support transitive dev dependencies , so 
    "django-extensions>=4.1",

    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",

    # XXX CommandError: Could not load shell runner: 'IPython Notebook' https://github.com/django-extensions/django-extensions/issues/1835#issuecomment-3035536658
    "notebook==6.5.4",
    "traitlets==5.9.0",

]

[tool.uv.sources]
mysite = { workspace = true }
# predict = { workspace = true }

[tool.uv.workspace]
members = [
    "mysite",
    # "predict",
]
