[project]
name = "label-train-serve-workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "label-train-serve",
    "site-example",
]

[tool.uv.sources]
label-train-serve = { workspace = true }
site-example = { workspace = true }
