# Generated by Django 6.0.1 on 2026-02-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kedrogy", "0002_djangodataset_image_djangodataset_pipeline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labels", models.CharField(default="N/A", max_length=400)),
                (
                    "on_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kedrogy.djangodataset",
                    ),
                ),
            ],
        ),
    ]
