# Generated by Django 6.0.2 on 2026-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedrogy', '0004_djangolastdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangomodel',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
