# Generated by Django 6.0.2 on 2026-02-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedrogy', '0005_djangomodel_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangomodel',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
