# Generated by Django 6.0.2 on 2026-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kedrogy', '0006_djangomodel_served'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangodataset',
            name='recipe',
        ),
    ]
