# Generated by Django 6.0.2 on 2026-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kedrogy', '0007_remove_djangodataset_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangodataset',
            name='data_table_name',
            field=models.CharField(default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='djangodataset',
            name='id_field',
            field=models.CharField(default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='djangomodel',
            name='a_preprocess_fun',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
