# Generated by Django 6.0.4 on 2026-09-24 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedrogy", "0009_djangomodel_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangomodel",
            name="artifact_status",
            field=models.CharField(default="UNVERIFIED", max_length=16),
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("VERIFYING", "Verifying"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("TIMED_OUT", "Timed Out"),
                            ("INTERRUPTED", "Interrupted"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("namespace", models.CharField(max_length=63)),
                ("job_name", models.CharField(max_length=63, unique=True)),
                ("job_uid", models.CharField(blank=True, max_length=64)),
                ("attempts", models.JSONField(default=list)),
                ("artifact", models.JSONField(default=dict)),
                ("error", models.JSONField(default=dict)),
                ("public_logs", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("heartbeat_at", models.DateTimeField(null=True)),
                ("lease_owner", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to="kedrogy.djangomodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="djangomodel",
            name="published_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="kedrogy.trainingrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingrun",
            constraint=models.UniqueConstraint(
                fields=("model", "idempotency_key"), name="unique_training_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["QUEUED", "RUNNING", "VERIFYING"])),
                fields=("model",),
                name="one_active_training_run",
            ),
        ),
    ]
