# Generated by Django 6.0.4 on 2026-09-24 21:57

import django.db.models.deletion
import kedrogy.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedrogy", "0010_djangomodel_artifact_status_trainingrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangodataset",
            name="binding_state",
            field=models.CharField(default="UNRESOLVED", max_length=16),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="prodigy_dataset_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="prodigy_dataset_name",
            field=models.CharField(
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="djangomodel",
            name="label_schema",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djangomodel",
            name="resources_deleting",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ServingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("snapshot", models.JSONField(default=dict)),
                ("namespace", models.CharField(max_length=63)),
                ("deployment_uid", models.CharField(blank=True, max_length=64)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(default="STARTING", max_length=16)),
                ("startup_status", models.CharField(default="RUNNING", max_length=16)),
                ("error", models.JSONField(default=dict)),
                ("startup_error", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(null=True)),
                ("observed_at", models.DateTimeField(null=True)),
                ("stopped_at", models.DateTimeField(null=True)),
                ("lease_owner", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serving_runs",
                        to="kedrogy.djangomodel",
                    ),
                ),
                (
                    "training_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serving_runs",
                        to="kedrogy.trainingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="djangomodel",
            name="current_serving",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="kedrogy.servingrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="servingrun",
            constraint=models.UniqueConstraint(
                fields=("model", "idempotency_key"), name="unique_serving_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="servingrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["STARTING", "READY", "UNAVAILABLE", "STOPPING"])
                ),
                fields=("model",),
                name="one_live_serving_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="servingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "STARTING",
                            "READY",
                            "UNAVAILABLE",
                            "FAILED",
                            "STOPPING",
                            "STOPPED",
                        ],
                    )
                ),
                name="valid_serving_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="servingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("startup_status__in", ["RUNNING", "SUCCEEDED", "FAILED"])
                ),
                name="valid_serving_startup_status",
            ),
        ),
        migrations.AlterField(
            model_name="djangodataset", name="prodigy_dataset_name",
            field=models.CharField(default=kedrogy.models.new_annotation_key, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="djangodataset", name="binding_state",
            field=models.CharField(default="PENDING", max_length=16),
        ),
    ]
