# Generated by Django 6.0.4 on 2026-09-26 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedrogy", "0013_normalize_legacy_drafts"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangodataset",
            name="annotation_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="annotation_observed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="annotation_refresh_requested",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="annotations_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="deletion_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djangomodel",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="artifact_removed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="djangomodel",
            name="on_dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kedrogy.djangodataset"
            ),
        ),
        migrations.AlterField(
            model_name="servingrun",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serving_runs",
                to="kedrogy.djangomodel",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrun",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="training_runs",
                to="kedrogy.djangomodel",
            ),
        ),
        migrations.CreateModel(
            name="AnnotationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.CharField(max_length=63)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("snapshot", models.JSONField(default=dict)),
                ("resources", models.JSONField(default=list)),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="STARTING", max_length=16)),
                ("startup_status", models.CharField(default="RUNNING", max_length=16)),
                ("startup_error", models.JSONField(default=dict)),
                ("error", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("observed_at", models.DateTimeField(null=True)),
                ("stopped_at", models.DateTimeField(null=True)),
                ("lease_owner", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annotation_runs",
                        to="kedrogy.djangodataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationSlot",
            fields=[
                (
                    "namespace",
                    models.CharField(max_length=63, primary_key=True, serialize=False),
                ),
                (
                    "run",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slot",
                        to="kedrogy.annotationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeletionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target", models.CharField(max_length=80)),
                ("action", models.CharField(max_length=24)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("plan", models.JSONField(default=dict)),
                ("completed", models.JSONField(default=list)),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="QUEUED", max_length=16)),
                (
                    "step",
                    models.CharField(default="Waiting for cleanup", max_length=200),
                ),
                ("error", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("lease_owner", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_runs",
                        to="kedrogy.djangodataset",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_runs",
                        to="kedrogy.djangomodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="annotationrun",
            constraint=models.UniqueConstraint(
                fields=("dataset", "idempotency_key"), name="unique_annotation_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["STARTING", "READY", "UNAVAILABLE", "STOPPING", "STOPPED"],
                    )
                ),
                name="valid_annotation_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("startup_status__in", ["RUNNING", "SUCCEEDED", "FAILED"])
                ),
                name="valid_annotation_startup",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionrun",
            constraint=models.UniqueConstraint(
                fields=("target", "idempotency_key"), name="unique_deletion_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SUCCEEDED"), _negated=True),
                fields=("target",),
                name="one_pending_deletion",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "QUEUED",
                            "RUNNING",
                            "RETRY_WAIT",
                            "NEEDS_REVIEW",
                            "SUCCEEDED",
                        ],
                    )
                ),
                name="valid_deletion_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="deletionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("action__in", ["model_files", "model", "dataset", "annotations"])
                ),
                name="valid_deletion_action",
            ),
        ),
    ]
