# Generated by Django 6.0.4 on 2026-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedrogy", "0014_durable_annotation_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="servingrun",
            name="cleanup_observed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="servingrun",
            name="lease_epoch",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="servingrun",
            name="resource_layout",
            field=models.CharField(default="legacy-fixed-v1", max_length=24),
        ),
        migrations.AddField(
            model_name="servingrun",
            name="resource_plan",
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name="servingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resource_layout__in", ["legacy-fixed-v1", "run-owned-v2"])
                ),
                name="valid_serving_layout",
            ),
        ),
    ]
