# Generated by Django 6.0.4 on 2026-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedrogy", "0015_serving_resource_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangodataset",
            name="annotation_policy",
            field=models.CharField(default="reject-other-v1", max_length=32),
        ),
        migrations.AlterField(
            model_name="djangodataset",
            name="annotation_policy",
            field=models.CharField(default="single-label-choice-v2", max_length=32),
        ),
        migrations.AddField(
            model_name="djangodataset",
            name="source_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
