# Generated by Django 6.0.4 on 2026-10-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedrogy", "0016_annotation_identity_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangomodel",
            name="legacy_cleanup_review",
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
