[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "site-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "label-train-serve",
    "psycopg[binary,pool]",
    "uvicorn==0.34.3",#pin to version which prodigy 1.18.4 wants
]

[dependency-groups]
dev = [
]

[tool.uv]
package = true

[tool.uv.sources]
label-train-serve = { path = "../label-train-serve", editable = true }

[project.scripts]
tools-manage = "site_example.manage:main"

# [tool.setuptools.packages.find]
# exclude = ['static', 'templates']
