[project]
name = "mykedro"
version = "0.1.0"
authors = [
    { name = "team ysz", email = "team@ysz.vc" }
]
requires-python = ">=3.12"
dependencies = [
    "kedro>=1.2.0",
    "kedro-datasets[pandas]>=9.1.1",
    "ysz-kedro-datasets>=0.1.5",
    "psycopg[binary,pool]",
    "scikit-learn>=1.7.2",
    "prodigy>=1.18.4",
    "psycopg2>=2.9.11",#prodigy+postgres
    #train pipeline
    "datasets>=4.4.1",
    "transformers==4.57.1",
    "torch>=1.13.1",
    "evaluate>=0.4.6",
    "accelerate>=1.11.0",
    "predict",
    "kedro-viz>=12.3.0",
]

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[tool.kedro]
package_name = "mykedro"
project_name = "mykedro"
kedro_init_version = "1.2.0"
source_dir = "src"

[tool.uv]
package = true

[tool.kedro_telemetry]
project_id = "14909e7c5e8c47b582918cc118916796"

# [[tool.uv.index]]
# name = "ysz"
# url = "https://pypi.ysz.vc/"
# ignore-error-codes = [422]
# # https://docs.astral.sh/uv/concepts/indexes/#pinning-a-package-to-an-index
# # prevent packages from being installed from here unless explicitly pinned to it
# explicit = true

[tool.uv.sources]
# and pin 
ysz-kedro-datasets = { git = "ssh://git@github.com/ysz-vc/kedro-datasets", tag = "v0.1.5" }
# and pin prodigy 
prodigy = { index = "prodigy" }
# development 
# ysz-kedro-datasets = { path = "../../../kedro-datasets", editable = true }
predict = { path = "../../predict", editable = true }

[[tool.uv.index]]
name = "prodigy"
url = "https://download.prodi.gy"
ignore-error-codes = [422]
# https://docs.astral.sh/uv/concepts/indexes/#pinning-a-package-to-an-index
# prevent packages from being installed from here unless explicitly pinned to it
explicit = true

[project.entry-points.'ysz.predict']
a_preprocess_fun = "mykedro.preprocess:preprocess_fun"
