[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kedrogy"
version = "0.1"
dependencies = [
    "django>=6.0.1",
    "django-htmx>=1.27.0",
    "django-tasks",#see tool.uv.sources
    "psycopg[binary,pool]",
    "jinja2",

    "prodigy>=1.18.4",
    "psycopg2>=2.9.11",
]
description = "A Django apps."
readme = "README.rst"
license = "BSD-3-Clause"
requires-python = ">=3.12"
authors = [
    {name = "Team Ysz", email = "team@ysz.vc"},
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.urls]
Homepage = "https://www.example.com/"

# [tool.setuptools.packages.find]
# exclude = ['notebooks*', 'kedrogy_site*']

[tool.uv]
package = true

[tool.uv.sources]
django-tasks = { git = "https://github.com/RealOrangeOne/django-tasks.git", rev = "4377f2c" }
# add like this
# uv add --package django-dataset-new git+ssh://github.com/RealOrangeOne/django-tasks.git --rev 4377f2c

# and pin prodigy 
prodigy = { index = "prodigy" }

[[tool.uv.index]]
name = "prodigy"
url = "https://download.prodi.gy"
ignore-error-codes = [422]
# https://docs.astral.sh/uv/concepts/indexes/#pinning-a-package-to-an-index
# prevent packages from being installed from here unless explicitly pinned to it
explicit = true

[[tool.uv.index]]
name = "ysz"
url = "https://pypi.ysz.vc/"
publish-url = "https://pypi.ysz.vc/"
explicit = true
