# Generated by Django 6.0.1 on 2026-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_train_serve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangodataset',
            name='image',
            field=models.CharField(default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='djangodataset',
            name='pipeline',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='djangodataset',
            name='recipe',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='djangodataset',
            name='recipe_options',
            field=models.CharField(default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='djangodataset',
            name='workingDir',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
