# Generated by Django 6.0.2 on 2026-02-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_train_serve', '0003_djangomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoLastDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_train_serve.djangodataset')),
            ],
        ),
    ]
