apiVersion: v1
kind: Service
metadata:
  name: prodigy-svc
spec:
  selector:
    app.kubernetes.io/name: prodigy
  ports:
    - name: prodigy
      protocol: TCP
      port: 8080
      targetPort: 8080
---
# https://support.prodi.gy/t/feature-request-url-prefixing/1898/2
# # strip prefix /label-{{ dataset_name }}
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: label-news-headlines-middleware
# spec:
#   stripPrefix:
#     forceSlash: false
#     prefixes:
#       # NB replace _ with - , k8s requirement above
#       - /label-news-headlines
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prodigy-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    # traefik.ingress.kubernetes.io/router.middlewares: default-label-news-headlines-middleware@kubernetescrd
spec:
  rules:
    - http:
        paths:
          # - path: /label-news-headlines
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prodigy-svc
                port:
                  number: 8080
