"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def required_setting(name: str) -> str:
    """Load a secret without a shared default or exposing its value."""
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(f"Set {name} in the local environment or Kubernetes Secret.")
    return value


SECRET_KEY = required_setting("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django_htmx",
    "kedrogy.apps.DatasetNewConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_tasks",
    "django_tasks.backends.database",
    # for notebooks
    "django_extensions",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "mysite.errors.APIBoundaryMiddleware",
    "mysite.errors.TrustedProxyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            # # disable caching?
            # # https://docs.djangoproject.com/en/6.0/ref/templates/api/
            # 'loaders': [
            #     'django.template.loaders.filesystem.Loader',
            #     'django.template.loaders.app_directories.Loader',
            # ],
            # # or
            # # k rollout restart deployment mysite
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # "OPTIONS": {
        #     "options": "-c search_path=django_schema"  # ensure: create schema django_schema;
        # },
        "NAME": os.environ["PGDATABASE"],
        "USER": os.environ["PGUSER"],
        "PASSWORD": os.environ["PGPASSWORD"],
        "HOST": os.environ["PGHOST"],
        "PORT": os.environ["PGPORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("ru", "Russian"),
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "kedrogy", "locale"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

TASKS = {
    "default": {
        "BACKEND": "django_tasks.backends.database.DatabaseBackend",
    },
}

# XXX https://docs.djangoproject.com/en/6.0/howto/static-files/ and https://stackoverflow.com/a/78760859 and
STATIC_ROOT = str(Path(__file__).resolve().parents[2] / "static")

# CORS
CORS_ALLOWED_ORIGINS = []

CORS_ALLOW_CREDENTIALS = True

# DRF
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "mysite.errors.api_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# These settings are controlled by the operator, not by API payloads.
KEDROGY_NAMESPACE = os.environ.get("KEDROGY_NAMESPACE", "default")
KEDROGY_ML_IMAGE = required_setting("KEDROGY_ML_IMAGE")
KEDROGY_ML_IMAGE_ALIASES = frozenset(json.loads(os.environ.get(
    "KEDROGY_ML_IMAGE_ALIASES", '["kedrogy-registry:5000/mykedro:latest"]'
))) | {KEDROGY_ML_IMAGE}
KEDROGY_SOURCES = json.loads(os.environ.get(
    "KEDROGY_SOURCES", '{"all_data":{"schema":"public","table":"all_data","id_fields":["id"]}}'
))

KEDROGY_TRAIN_TIMEOUT = int(os.environ.get("KEDROGY_TRAIN_TIMEOUT", "3600"))
KEDROGY_TRAIN_OPTIONS = json.loads(os.environ.get("KEDROGY_TRAIN_OPTIONS", "{}"))
TRUSTED_PROXY_CIDRS = []
CSRF_FAILURE_VIEW = "mysite.errors.csrf_failure"
LOGGING = {
    "version": 1, "disable_existing_loggers": False,
    "filters": {"redact": {"()": "mysite.errors.RedactFilter"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "filters": ["redact"]}},
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {"django": {"handlers": ["console"], "propagate": False, "level": "INFO"}},
}

# A separate read-only identity is used for annotation preflight.
def annotation_reader_config():
    from dotenv import dotenv_values
    filename = os.environ.get("KEDROGY_READER_ENV_FILE")
    values = dotenv_values(filename) if filename else {}
    return {target: os.environ.get("READER_" + source, values.get(source, ""))
            for source, target in [("PGHOST", "host"), ("PGPORT", "port"),
                                   ("PGDATABASE", "dbname"), ("PGUSER", "user"), ("PGPASSWORD", "password")]}

KEDROGY_READER_CONFIG = annotation_reader_config()
KEDROGY_MAX_ANNOTATIONS = int(os.environ.get("KEDROGY_MAX_ANNOTATIONS", "100000"))
KEDROGY_SERVE_TIMEOUT = int(os.environ.get("KEDROGY_SERVE_TIMEOUT", "300"))
KEDROGY_SERVE_FRESHNESS = int(os.environ.get("KEDROGY_SERVE_FRESHNESS", "30"))
KEDROGY_SERVE_INTERVAL = int(os.environ.get("KEDROGY_SERVE_INTERVAL", "10"))

# Annotation startup outcome and data freshness are independent.
KEDROGY_ANNOTATION_TIMEOUT = int(os.environ.get("KEDROGY_ANNOTATION_TIMEOUT", "600"))
KEDROGY_ANNOTATION_FRESHNESS = 45
KEDROGY_ANNOTATION_DATA_FRESHNESS = 300
KEDROGY_ANNOTATION_URL = os.environ.get("KEDROGY_ANNOTATION_URL", "http://label.localhost")
KEDROGY_CLEANUP_TIMEOUT = int(os.environ.get("KEDROGY_CLEANUP_TIMEOUT", "900"))
