name: build and push to pypi.ysz.vc

on:
  workflow_dispatch:

  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "./kedrogy/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.28"

      - name: Build
        run: uv build
        working-directory: ./kedrogy

      - name: Publish
        run: uv publish --index ysz
        env:
          UV_PUBLISH_USERNAME: ${{ vars.UV_PUBLISH_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.UV_PUBLISH_PASSWORD }}
        working-directory: ./kedrogy
